spring.application.name=ToDoList
spring.datasource.url=jdbc:postgresql://localhost:5433/TodoList
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mysupersecretkeymysupersecretkey1234   # must be at least 32 chars
jwt.expiration=86400000                           # 24 hours in milliseconds